import assert from 'node:assert/strict';import {Game,pathfind} from '../dist/engine.js';import {C,upgrades} from '../dist/config.js';
let seed=42;const rng=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296};
const g=new Game(rng);g.prepare();assert.equal(g.state,'prep');
const near=pathfind({x:4,y:4},{x:3,y:5},g.facilities).length;const far=pathfind({x:4,y:4},{x:20,y:9},g.facilities).length;assert(far>near);const f=g.facilities[0],o=g.onis[0];const fit=g.rate(f,o);assert.equal(fit/g.rate(f,{...o,type:'repair'}),1.25);const speed=g.speed(o);g.buffs.speed=1;assert(g.speed(o)>speed);g.buffs={};g.heat=60;assert(g.heatEffect(o).drain>1);assert(g.heatEffect(o).recovery<1);g.heat=0;
assert(!g.move(f.id,7,6));assert(g.move(f.id,3,8));assert(g.move(f.id,3,6));assert(g.assign(o.id,g.facilities[1].id));assert(g.assign(o.id,f.id));
const report=[];for(let wave=1;wave<=8;wave++){if(wave===3){for(const [type,x,y]of [['compost',11,6],['repair',15,6]]){assert(g.build(type,x,y));const facility=g.facilities.at(-1);assert(g.recruit());g.assign(g.onis.at(-1).id,facility.id)}}if(wave===4){assert(g.build('break',19,6));assert(g.recruit());g.assign(g.onis.at(-1).id,g.facilities.at(-1).id)}if(wave>=5&&g.onis.length<10&&g.money>=C.oniPrice){g.recruit();g.assign(g.onis.at(-1).id,g.facilities[(wave-5)%g.facilities.length].id)}assert(g.startWave());assert(g.command());assert(!g.command());let ticks=0;while(g.state==='wave'&&ticks++<12000){g.tick(.05);assert(g.activeItems()<=C.maxItems);assert(g.trucks.length<=3)}assert(ticks<12000);report.push({wave,profit:g.profit,heat:+g.heat.toFixed(2),rescued:g.rescued,total:g.total});if(wave<8){assert.equal(g.state,'upgrade');assert.equal(g.choices.length,3);assert.equal(new Set(g.choices.map(x=>x.id)).size,3);assert(g.choose(g.choices.find(u=>u.id==='eco')?.id||g.choices[0].id));assert(!g.choose(g.choices[0].id))}}assert.equal(g.state,'result');assert(g.clear);assert(g.profit>0);assert(g.maxFlow>1);assert(g.burned>0);g.reset();assert.equal(g.state,'title');assert.equal(g.wave,0);
const failure=new Game(()=>.5);failure.prepare();failure.startWave();failure.heat=99.9;failure.burn([{type:'battery'}]);failure.tick(.05);assert.equal(failure.state,'result');assert.equal(failure.clear,false);
for(const u of upgrades){const a=new Game(()=>.5);a.state='upgrade';a.choices=[u];assert(a.choose(u.id));assert.equal(a.buffs[u.id],1)}
console.log(JSON.stringify({status:'PASS',distance:{near,far},affinity:fit,run:report},null,2));
function delivery(y,type='press',heat=0){const a=new Game(()=>.4);a.facilities=[];a.onis=[];const f=a.addFacility('press',7,y);const o=a.addOni(type,f.id);o.trait='careful';a.prepare();a.startWave();a.nextSpawn=999;a.heat=heat;a.trucks=[{id:999,x:7,items:[{id:1000,type:'card',route:['press'],step:0,owner:null}]}];a.total=1;let time=0;while(!a.profit&&time<30){a.tick(.025);time+=.025}return{time,profit:a.profit}}
const closeDelivery=delivery(6),farDelivery=delivery(9),unmatched=delivery(6,'wash');assert(closeDelivery.profit>0);assert(farDelivery.profit>0);assert(farDelivery.time>closeDelivery.time);assert(unmatched.time>closeDelivery.time);console.log({closeDelivery,farDelivery,unmatched});
const hot=new Game(()=>.1);const hotOni=hot.onis[0];hot.heat=80;assert(hot.heatEffect({...hotOni,trait:'cool'}).drain<hot.heatEffect({...hotOni,trait:'fast'}).drain);const recovery=hot.heatEffect(hotOni).recovery;hot.buffs.shade=1;assert(hot.heatEffect(hotOni).recovery>recovery);const washRate=hot.rate(hot.facilities[0],hotOni);hot.buffs.wash=1;assert(hot.rate(hot.facilities[0],hotOni)>washRate);const cap=hot.capacity(hot.facilities[0]);hot.buffs.buffer=1;assert.equal(hot.capacity(hot.facilities[0]),cap+1);hot.prepare();hot.buffs.water=1;hotOni.stamina=1;hot.startWave();assert.equal(hotOni.stamina,hotOni.max);hot.buffs.eco=1;hot.heat=0;hot.burn([{type:'battery'}]);assert(Math.abs(hot.heat-4.5*C.heatScale*.85)<.001);

