// Development-only harness injected by visual-server.mjs. Never shipped in dist.
const qaPanel=document.createElement('aside');qaPanel.id='qa-panel';qaPanel.style='position:fixed;right:8px;top:106px;z-index:50;background:#07151fee;color:white;padding:6px;font:12px monospace;max-width:440px;max-height:45vh;overflow:auto;border:1px solid #789';
const qaOut=document.createElement('pre');qaOut.id='qa-results';qaOut.style='white-space:pre-wrap';const qaControls=document.createElement('div');qaPanel.append(qaControls,qaOut);document.body.append(qaPanel);
function qb(name,fn){const b=document.createElement('button');b.textContent=name;b.style='font:12px monospace;padding:4px;min-height:30px';b.onclick=fn;qaControls.append(b)}
qb('QA showcase',()=>{game.reset();game.prepare();game.money=5000;for(const [type,x]of [['break',11],['repair',15],['compost',19]]){const f=game.addFacility(type,x,6);game.addOni(type,f.id)}game.startWave();for(let i=0;i<360;i++)game.tick(.025);game.flow=15;refresh();qaOut.textContent='Showcase fixture. Gameplay balance is unchanged.'});
qb('QA 8 Waves',()=>{try{game.reset();game.prepare();const run=[];for(let wave=1;wave<=8;wave++){if(wave===3){for(const [type,x]of [['compost',11],['repair',15]]){if(game.build(type,x,6)){game.recruit();game.assign(game.onis.at(-1).id,game.facilities.at(-1).id)}}}if(wave===4&&game.build('break',19,6)){game.recruit();game.assign(game.onis.at(-1).id,game.facilities.at(-1).id)}game.startWave();game.command();for(let i=0;i<20000&&game.state==='wave';i++)game.tick(.05);run.push({wave:game.wave,state:game.state,profit:game.profit,heat:game.heat});if(game.state==='result')break;game.choose(game.choices[0].id)}refresh();qaOut.textContent=JSON.stringify({pass:game.clear&&game.wave===8,run},null,2)}catch(e){qaOut.textContent='FAIL '+e.stack}});
qb('QA measure 10s',()=>{const start=performance.now(),samples=[],costs=[];let prev=start;const original=renderer.draw.bind(renderer);renderer.draw=(...args)=>{const t=performance.now();samples.push(t-prev);prev=t;original(...args);costs.push(performance.now()-t)};qaOut.textContent='Measuring 10 seconds…';setTimeout(()=>{renderer.draw=original;const resources=performance.getEntriesByType('resource');const sorted=costs.sort((a,b)=>a-b);qaOut.textContent=JSON.stringify({viewport:[innerWidth,innerHeight],fps:+(samples.length/((performance.now()-start)/1000)).toFixed(1),drawMsP95:+(sorted[Math.floor(sorted.length*.95)]||0).toFixed(2),dom:document.querySelectorAll('*').length,heapMB:performance.memory?+(performance.memory.usedJSHeapSize/1048576).toFixed(1):null,lcpMs:Math.round(window.qaLCP),transferBytes:resources.reduce((n,r)=>n+r.transferSize,0),decodedBytes:resources.reduce((n,r)=>n+r.decodedBodySize,0),images:resources.filter(r=>r.name.endsWith('.webp')).map(r=>r.name.split('/').pop()),overflow:document.documentElement.scrollWidth>innerWidth},null,2)},10000)});
qb('QA hide',()=>{qaPanel.style.display='none'});
qb('QA cargo gallery',async()=>{const cargo=renderer.art.get('cargo');if(!cargo){qaOut.textContent='Loading cargo, open gallery again.';return}const panel=document.createElement('div');panel.id='cargo-gallery';panel.style='position:fixed;inset:20% 5%;background:#d8c09c;z-index:60;padding:12px;color:#183443';panel.innerHTML='<b>運搬物の形 / Cargo silhouettes</b><button id="gallery-close">閉じる / Close</button>';const c=document.createElement('canvas');c.width=1050;c.height=220;c.style='height:180px;width:100%';panel.append(c);document.body.append(panel);panel.querySelector('button').onclick=()=>panel.remove();const ctx=c.getContext('2d');['pet','can','card','cloth','phone','battery','food'].forEach((type,i)=>{ctx.drawImage(cargo,(i%4)*128,Math.floor(i/4)*128,128,128,15+i*150,30,120,120);ctx.fillStyle='#183443';ctx.font='20px system-ui';ctx.textAlign='center';ctx.fillText(type,75+i*150,190)})});
qb('QA empty truck',()=>{game.reset();game.prepare();game.trucks=[{id:900,x:7,items:[]}];refresh();qaOut.textContent='Empty load fixture: zero items; empty truck image and label expected.'});
qb('QA rally',()=>{game.reset();game.prepare();game.startWave();game.command();refresh();qaOut.textContent='Foreman should shout for 6 seconds, then return to calm.'});
qb('QA sprites',()=>{game.reset();game.prepare();game.money=5000;for(const [type,x]of [['break',11],['repair',15],['compost',19]]){const f=game.addFacility(type,x,6);game.addOni(type,f.id)}game.startWave();for(let i=0;i<200;i++)game.tick(.025);refresh();renderer.camera.zoomAt(1.8);updateZoom();qaOut.textContent='Directional profiles: side facing right/left, back when moving up, front when moving down.'});
